name: Deploy Azure Functions

on:
  pull_request:
    branches:
      - deploy-ci
    types:
      - closed

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Publish All Functions
        run: |
          dotnet publish ./AzureFunctions/AzureFunctions.csproj --configuration Release --output ./publish
        shell: pwsh

      - name: Deploy to Azure Function App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          package: ./publish
